service: serverless_hello_world
frameworkVersion: '2'
app:my-aws-python-flask-api-app
provider:
  name: aws
  runtime: python3.8

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - httpApi:
          path: /time
          method: get